### ISSUE TITLE
Building Tag 8.1 fails to get SVN Repos

### ISSUE THREAD

**Issue by SerethiX** [apple/ccs-calendarserver#409]
I checked out Tag 8.1 and tried to build, but when I run the programm it failes with "Access to (INSERT SVN REPO URL) not allowed"

When you Access the SVN Repo in a Browser it redirects to gitHub.

I checked against master and see that you moved all over to git, but the old code stopped working then.

Is it save to run master branch?

**Comment by ryandesign** [comment]
I switched off the old Subversion repositories yesterday and put in the redirects to GitHub. This is for the benefit of anybody browsing the code on the web. If Calendar Server's build system requires access to the Subversion repositories, that's not going to work anymore.

**Comment by dreness** [comment]
Yes, safe to run master.

In the move from SVN to GIT, only master was updated to include the necessary changes to the dependency resolution / build scripts. In general it's good to stick to release tags, but in this case master is your best bet and is not any less stable than the 8.1 tag. Here's a comparison of 8.1 to master: https://github.com/apple/ccs-calendarserver/compare/CalendarServer-8.1...master

If we're not going to go back and fix the setup / build in all the previous tags, perhaps we can at least tag a newer release, so people who pick the latest release will get something that works.

Also, unrelated, ./bin/develop is failing to download memcached because www.memcached.org appears to be offline. Hopefully it comes back soon... (update at 2:48 p.m. PST: www.memcached.org is up)

**Comment by SerethiX** [comment]
Jeah, I got a little further, now I'm stuck with this:

```
Downloading xattr-0.8.0.tar.gz
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-siizN_/xattr/
```

I already installed pip and tried some stackoverflow suggestions, unfortunatly I'm not an expert for python and it's dependency system. Can you help me with that issue?

Am I headig in the right direction if I want to use the Server?

**Comment by dreness** [comment]
@Serethi what OS / version are you using? There have been some problems building the xattr module, mostly on freebsd I think. Indeed the [docs](https://pypi.python.org/pypi/xattr/) say that support for freebsd and solaris is 'experimental', but is supported on OS X and Linux. One common reason it might fail is if your partition / filesystem is not configured to enable extended attributes. In linux, this can be done by adding the 'user_xattr' mount option.

This module is here to support upgrades from ancient versions of CalendarServer, which you probably don't need to do. I spent a little time yesterday trying to tease it out, but so far have not succeeded in doing that.

Perhaps with more info about why xattr is failing, that can be fixed or worked around. Try a manual installation of xattr in verbose mode to see if we can get some failure details:

```
virtualenv xatest
cd xatest
source bin/activate
pip install -vvv xattr
```

You can then use the shell function 'deactivate' (added by 'activate') to exit this virtualenv, or just close the shell.
